language: java
jdk:
 - oraclejdk8

sudo: false # faster builds

script:
  - java -version
  - echo $JAVA_HOME
  - mvn -version
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
