language: java
sudo: false
jdk:
 - oraclejdk8
 
before_install:
 - chmod +x mvnw


script:
    - mvn clean cobertura:cobertura -Dspring.profiles.active=dev


after_success:
  - bash <(curl -s https://codecov.io/bash)
